1. Create a null vector of size 10

In [1]:
import numpy as np
vector = np.zeros(10, dtype = int)
vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

2. How to find the memory size of an array

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
m = arr.itemsize
n = arr.size
print('Memory Size:', m*n)

Memory Size: 24


3. Create a null vector of size 10 but the fifth value which is 1

In [3]:
import numpy as np
arr = np.zeros(10, dtype = int)
arr[4] = 1
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

4. Create a vector with values ranging from 15 to 45

In [4]:
vect = np.arange(15,46)
vect

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

5. Reverse a vector (The first element becomes last)

In [5]:
vect = np.arange(0,10)
vect = vect[::-1]
vect

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

6. Write a NumPy program to add, subtract, multiply, divide arguments element-wise

In [6]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print("Add:", np.add(arr1, arr2))
print("Sub:", np.subtract(arr1, arr2))
print("Mul:", np.multiply(arr1, arr2))
print("Divide:", np.divide(arr1, arr2))

Add: [ 7  9 11 13 15]
Sub: [-5 -5 -5 -5 -5]
Mul: [ 6 14 24 36 50]
Divide: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


7. Write a NumPy program to round elements of the array to the nearest integer

In [7]:
arr1=np.array([1.6,2.3,3.7,4.4,5.9])
print("using round function:",np.array(np.round(arr1),dtype=int))
print("using ceil function:",np.array(np.ceil(arr1),dtype=int))
print("using floor function:",np.array(np.floor(arr1),dtype=int))

using round function: [2 2 4 4 6]
using ceil function: [2 3 4 5 6]
using floor function: [1 2 3 4 5]


8. Write a NumPy program to get the floor and ceiling values of the elements of a NumPy array

In [8]:
arr1=np.array([1.6,2.3,3.7,4.4,5.9])
print("using ceil function:",np.ceil(arr1))
print("using floor function:",np.floor(arr1))

using ceil function: [2. 3. 4. 5. 6.]
using floor function: [1. 2. 3. 4. 5.]


9. Write a NumPy program to calculate mean across dimensions, in a 2D NumPy array.

In [9]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

[4. 5. 6.]
[2. 5. 8.]


10. Write a NumPy program to convert angles from degrees to radians for all elements in a given array.

In [10]:
deg_angle=np.array([0,30,45,60,90])
for i in deg_angle:
    print(np.deg2rad(i), end=' ')
print()
print(np.deg2rad(deg_angle))

0.0 0.5235987755982988 0.7853981633974483 1.0471975511965976 1.5707963267948966 
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


11. What is the use of all and any function in numpy?

The numpy.any() function tests whether any array elements along the mentioned axis evaluate to True.  
The numpy.all() function tests whether all array elements along the mentioned axis evaluate to True.

12. Create a 3x3 matrix with values ranging from 0 to 8
[[0 1 2]
[3 4 5]
[6 7 8]]

In [11]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

13. How to reverse the columns of a 2D array?

In [12]:
([[2, 1, 0],
[5, 4, 3],
[8, 7, 6]])

[[2, 1, 0], [5, 4, 3], [8, 7, 6]]

14. How to reverse the rows of a 2D array?

In [13]:
[[6, 7, 8],
[3, 4, 5],
[0, 1, 2]]

[[6, 7, 8], [3, 4, 5], [0, 1, 2]]

15. Find indices of non-zero elements from [1,2,0,0,4,0]

In [14]:
##########################
arr1 =([1,2,0,0,4,0])
print(np.nonzero(arr1))
##########################
arr1 =([1,2,0,0,4,0])
print(np.where(arr1))

(array([0, 1, 4], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


16. Write a NumPy program to compute the determinant of an array.

In [15]:
arr=np.array([[1,2],[0,2]])
det= np.linalg.det(arr)
det

2.0

17. Write a NumPy program to compute the inverse of a given matrix

In [16]:
arr=np.array([[1,2],[0,2]])
print(arr)
inv=np.linalg.inv(arr)
inv

[[1 2]
 [0 2]]


array([[ 1. , -1. ],
       [ 0. ,  0.5]])

18. Create a random vector of size 30 and find the mean value

In [17]:
rand_arr=np.random.randint(1,20,30)
print('Random array of size 30:',rand_arr)
print("mean is :",np.mean(rand_arr))

Random array of size 30: [10 15 19 19 16  1  8 17 19  4  1 11  3  9  2  8  7  8 18 16 17  3 14 18
 11  1  9 11  8  3]
mean is : 10.2


19. How to extract all numbers between a given range from a NumPy array?

In [18]:
arr=np.array([i for i in range(20)])
print("using slicing:",arr[5:9])

using slicing: [5 6 7 8]


20. Create a 3x3x3 array with random values

In [19]:
arr1 = np.random.randint(20,40,(3,3,3))

print(arr1)

[[[29 39 36]
  [22 38 32]
  [22 27 21]]

 [[31 22 21]
  [37 23 31]
  [32 31 39]]

 [[31 22 29]
  [31 25 38]
  [31 32 35]]]


21. Create a 10x10 array with random values and find the minimum and maximum values

In [20]:
arr=np.random.randint(1,30,(10,10))
print(arr)
print(arr.max())
print(arr.min())

[[19 18 10 23 18 26 14 14  3 12]
 [11 27 22 17 27 16  7 23 14 17]
 [16 18 18 13  4 24 16  7 24  2]
 [14 15 16 25  1 10 21 27  6 18]
 [12 25  2 10  7 24 12 13 28 23]
 [16 29 14 11 18 12 12 22  8 11]
 [17 21 21 26 17  2 27 13 27  1]
 [24 24 28 11  2 22 26  7  9 12]
 [23  6 26 21 18 22 12 10  1 27]
 [ 9  6 12  1 15 10  4  9  8 27]]
29
1


22. Create a 2d array with 1 on the border and 0 inside

In [21]:
arr=np.ones([5,5])
print(arr)
arr[1:4,1:4]=0
print()
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


23. Create a 5x5 matrix with values 1,2,3,4 just
below the diagonal

In [22]:
arr=np.diag([1,2,3,4],k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

24. Create a 3x3 identity matrix

In [23]:
identity_mat=np.identity(3,dtype=int)
identity_mat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

25. Create a 8x8 matrix and fill it with a checkerboard pattern  
[[0 1 0 1 0 1 0 1]  
[1 0 1 0 1 0 1 0]  
[0 1 0 1 0 1 0 1]  
[1 0 1 0 1 0 1 0]  
[0 1 0 1 0 1 0 1]  
[1 0 1 0 1 0 1 0]  
[0 1 0 1 0 1 0 1]  
[1 0 1 0 1 0 1 0]]

In [24]:
chkbrd = np.zeros([8, 8], dtype=int)
chkbrd[1::2,::2] = 1
chkbrd[::2,1::2] = 1
chkbrd

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

26. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [25]:
a1 = np.array([[2,3,4],[3,4,5],[5,4,3],[3,2,3],[3,2,5]])

a2 = np.array([[2,3],[3,4],[5,4]])
real = np.dot(a1,a2)
print(real)

[[33 34]
 [43 45]
 [37 43]
 [27 29]
 [37 37]]


27. Given a 1D array, negate all elements which are between 3 and 8, in place

In [26]:
arr=np.array([i for i in range(15)])
print(arr)
arr[3:9]=np.multiply(arr[3:9],-1)
arr

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14])

28. How to round away from zero a float array?

In [27]:
import numpy as np
def round_array(x,y):
    return np.round(x,y)
test = np.array([32.11, 51.5, 0.112])
print(round_array(test,0))

[32. 52.  0.]


29. How to find common values between the two arrays?

In [28]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,4,5,6,7])
print('Common element in array:',np.intersect1d(arr1,arr2))

Common element in array: [3 4 5]


30. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [29]:
arr=np.random.rand(10)
arr

array([4.43830741e-04, 5.50322330e-02, 7.77152082e-01, 4.44681770e-01,
       4.21442952e-01, 3.77322667e-02, 6.13770458e-01, 3.52643065e-01,
       1.91411715e-01, 2.07127475e-01])

31. Create a random vector of size 10 and sort it

In [30]:
arr=np.random.randint(1,20,10)
print("Random Array:",arr)

print('Sorted Array:',np.sort(arr))

Random Array: [18  3 16 14 18  4  1 10 15 15]
Sorted Array: [ 1  3  4 10 14 15 15 16 18 18]


32. Create a 5x5 matrix with row values ranging from 0 to 4  
[[0. 1. 2. 3. 4.]  
 [0. 1. 2. 3. 4.]  
 [0. 1. 2. 3. 4.]  
 [0. 1. 2. 3. 4.]  
 [0. 1. 2. 3. 4.]]

In [31]:
arr1 = np.zeros([5,5])
arr2 = arr1+np.arange(0,5)
print(arr2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


33. Consider two random arrays A and B, check if they are equal

In [32]:
arr1=np.random.randint(1,10,5)
arr2=np.random.randint(1,10,5)
if np.allclose(arr1,arr2):
    print("array's are same")
else:
    print("Array's are not same")

Array's are not same


34. Create a random vector of size 10 and replace the maximum value by 0

In [33]:
arr1=np.random.randint(1,30,10)
print(arr1)
arr1[arr1.argmax()]=0
print(arr1)

[23 14 10 10  4  2 19 22 12 21]
[ 0 14 10 10  4  2 19 22 12 21]


35. How to find out multiple indices of an item?

In [34]:
arr1 = np.array([4,0,3,0,2,4,3,6,3])
indices = np.where(arr1 == 3)
print(indices)

(array([2, 6, 8], dtype=int64),)


36. What is the equivalent of enumerate for NumPy arrays?

In [35]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i,j in np.ndenumerate(arr):
    print(i,"->",j)

(0, 0) -> 1
(0, 1) -> 2
(0, 2) -> 3
(1, 0) -> 4
(1, 1) -> 5
(1, 2) -> 6
(2, 0) -> 7
(2, 1) -> 8
(2, 2) -> 9


37. How to sort an array by the nth column?

In [36]:
arr[arr[:,1].argsort()]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

38. How to swap two rows of an array?

In [37]:
arr=np.array([[9 ,5, 7],
[0, 3 ,7],
[0, 1, 9]])
print(arr)
arr[[0,1]]=arr[[1,0]] # swapping of 1st two row's
arr

[[9 5 7]
 [0 3 7]
 [0 1 9]]


array([[0, 3, 7],
       [9, 5, 7],
       [0, 1, 9]])

39. How to compute the mean of a NumPy array?

In [38]:
arr=np.array([[9 ,5, 7],
[0, 3 ,7],
[0, 1, 9]])
print(arr)
np.mean(arr)

[[9 5 7]
 [0 3 7]
 [0 1 9]]


4.555555555555555

40. How to compute the median of a NumPy array?

In [39]:
arr=np.array([[9 ,5, 7],
[0, 3 ,7],
[0, 1, 9]])
np.median(arr)

5.0

41. How to compute the standard deviation of a NumPy array?

In [40]:
arr=np.array([[9 ,5, 7],
[0, 3 ,7],
[0, 1, 9]])
np.std(arr)

3.467663674294941

42. How to compute the mode of a NumPy array

In [41]:
from scipy import stats
arr=np.array([9 ,5, 7,0, 3 ,7,0, 1, 9])
stats.mode(arr)

ModeResult(mode=array([0]), count=array([2]))

43. How to print only 3 decimal places in a python NumPy array

In [42]:
arr=np.array([0.12110113, 0.40035121, 0.92241944, 0.67946091, 0.56842447,
0.32889515, 0.41926619, 0.14454096, 0.00154814, 0.2518045 ])
arr=np.around(arr,decimals=3)
arr

array([0.121, 0.4  , 0.922, 0.679, 0.568, 0.329, 0.419, 0.145, 0.002,
       0.252])

44. Write a NumPy program to compute the inverse of a given matrix

In [43]:
arr = np.array([[1, 2, 3],[4, 9, 6],[7, 8, 9]])
np.linalg.inv(arr)

array([[-0.6875    , -0.125     ,  0.3125    ],
       [-0.125     ,  0.25      , -0.125     ],
       [ 0.64583333, -0.125     , -0.02083333]])

45. Write a NumPy program to compute the covariance matrix of two given arrays

In [44]:
arr1=np.array([1,2,0])
arr2=np.array([0,1,2])
np.cov(arr1,arr2)

array([[ 1. , -0.5],
       [-0.5,  1. ]])

46. How to find the most frequent value in a NumPy array?

In [45]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[4 7 4 9 4 2 5 5 6 0 5 3 9 1 2 9 2 4 6 4 6 6 1 4 6 0 9 7 0 8 9 0 8 4 6 3 1
 8 2 4]
Most frequent value in the above array:
4


47. How to convert 1D array to 3D array?

In [46]:
arr1=np.array([1,2,0])
print("dimension of array",arr1.ndim)
arr1=np.array(arr1,ndmin=3)
print("\ndimension of array",arr1.ndim)

dimension of array 1

dimension of array 3


48. How to convert 4D array to 2D array?

In [47]:
arr2=np.arange(1,28)
arr2=arr2.reshape([3,3,3])
print(arr2)
print("\ndimension of array",arr2.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

dimension of array 3


49. Create a Numpy array filled with all zeros

In [48]:
arr1 = np.zeros([4,3])

print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


50. Find the number of rows and columns of a given matrix using NumPy

In [49]:
arr=np.random.randint(1,30,(4,5))
print('Number of Rows in array:',arr.shape[0])
print('Number of Columns in array:',arr.shape[1])

Number of Rows in array: 4
Number of Columns in array: 5
